#pragma once

#define BOARD_PIN_LCD_SCLK 18
#define BOARD_PIN_LCD_MOSI 23
#define BOARD_PIN_LCD_MISO -1
#define BOARD_PIN_LCD_CS 5
#define BOARD_PIN_LCD_DC 16
#define BOARD_PIN_LCD_RST 17
#define BOARD_PIN_LCD_BL 4

#define BOARD_PIN_LED_PWM 25

#define BOARD_ADC_CHANNEL ADC_CHANNEL_0
#define BOARD_ADC_UNIT ADC_UNIT_1
#define BOARD_ADC_ATTEN ADC_ATTEN_DB_12
#define BOARD_ADC_BITWIDTH ADC_BITWIDTH_12
